# Generated by Django 2.1 on 2020-01-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nporder', '0003_auto_20200122_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nporder',
            name='is_changed',
            field=models.CharField(choices=[('是', '是'), ('否', '否')], default='是', max_length=20),
        ),
    ]
