# Generated by Django 2.1 on 2019-10-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nporder', '0003_auto_20191005_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nporder',
            name='create_time',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
