# Generated by Django 2.1 on 2019-10-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nporder', '0004_auto_20191006_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nporder',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
