# Generated by Django 2.1 on 2020-01-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nporder', '0004_auto_20200122_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='nporder',
            name='applicant',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
