# Generated by Django 2.1 on 2020-01-22 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nporder', '0005_nporder_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nporder',
            name='material_code',
        ),
        migrations.RemoveField(
            model_name='nporder',
            name='model_code',
        ),
        migrations.AddField(
            model_name='nporder',
            name='comment',
            field=models.TextField(null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='nporder',
            name='applicant',
            field=models.CharField(max_length=20, null=True, verbose_name='申请者'),
        ),
        migrations.AlterField(
            model_name='nporder',
            name='city',
            field=models.CharField(max_length=10, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='nporder',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='nporder',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='nporder',
            name='direction',
            field=models.CharField(choices=[('基础版', '基础版'), ('增强版', '增强版'), ('完整版', '完整版')], default='添加', max_length=20, verbose_name='包名称'),
        ),
        migrations.AlterField(
            model_name='nporder',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='nporder',
            name='is_changed',
            field=models.CharField(choices=[('是', '是'), ('否', '否')], default='是', max_length=20, verbose_name='线上是否更新'),
        ),
        migrations.AlterField(
            model_name='nporder',
            name='is_finished',
            field=models.CharField(choices=[('是', '是'), ('否', '否')], default='否', max_length=20, verbose_name='是否完成'),
        ),
        migrations.AlterField(
            model_name='nporder',
            name='order_no',
            field=models.CharField(max_length=20, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='nporder',
            name='vin',
            field=models.CharField(max_length=20, verbose_name='VIN'),
        ),
    ]
