# Generated by Django 2.1 on 2020-01-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nporder', '0006_auto_20200123_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='nporder',
            name='internal_order_no',
            field=models.CharField(max_length=20, null=True, verbose_name='内部单号'),
        ),
    ]
