# Generated by Django 2.1 on 2019-10-08 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nporder', '0007_auto_20191008_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nporder',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
