# Generated by Django 2.1 on 2019-10-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nporder', '0008_auto_20191008_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='nporder',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
