# Generated by Django 2.1 on 2019-10-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nporder', '0009_nporder_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nporder',
            name='direction',
            field=models.CharField(choices=[('添加', '添加'), ('删除', '删除')], default='add', max_length=20),
        ),
    ]
