# Generated by Django 2.1 on 2019-10-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nporder', '0010_auto_20191019_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='nporder',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nporder',
            name='has_np_in_vom',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nporder',
            name='is_combined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nporder',
            name='material_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nporder',
            name='model_code',
            field=models.CharField(blank=True, choices=[('ES6002', 'ES6002'), ('ES6003', 'ES6003'), ('ES8002', 'ES8002'), ('ES8003', 'ES8003'), ('ES8004', 'ES8004')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nporder',
            name='province',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nporder',
            name='vinbom_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='nporder',
            name='direction',
            field=models.CharField(choices=[('添加', '添加'), ('删除', '删除')], default='添加', max_length=20),
        ),
    ]
