# Generated by Django 2.1 on 2019-10-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nporder', '0011_auto_20191023_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nporder',
            name='is_changed',
            field=models.CharField(choices=[('是', '是'), ('否', '否')], default='否', max_length=20),
        ),
    ]
