# Generated by Django 2.1 on 2019-11-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelfDrivePoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfdrivepoint',
            name='is_handovered',
            field=models.CharField(choices=[('是', '是'), ('否', '否')], default='否', max_length=20),
        ),
        migrations.AlterField(
            model_name='selfdrivepoint',
            name='is_installed',
            field=models.CharField(choices=[('是', '是'), ('否', '否')], default='是', max_length=20),
        ),
    ]
